### ISSUE TITLE
Migrate NFT.Storage to Postgres

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/nft.storage#331]
The base PR for this migration is https://github.com/ipfs-shipyard/nft.storage/pull/263
## Tasks

- [x] SQL Schema
- [x] Endpoints using postgres client
- [x] normalize cidv1 https://github.com/web3-storage/web3-schema/pull/4
- [x] Add docs and scripts for local database setup to run tests https://github.com/ipfs-shipyard/nft.storage/pull/425
- [x] Add deals schema and logic https://github.com/ipfs-shipyard/nft.storage/pull/418
- [x] #454
- [x] #459
- [x] #461 https://github.com/ipfs-shipyard/nft.storage/pull/496
    - \+ setup foreign table materialized views refresh
- [x] #473 https://github.com/ipfs-shipyard/nft.storage/pull/491
- [x] metrics will query postgres directly from `/metrics` https://github.com/ipfs-shipyard/nft.storage/pull/495
- [x] handle DB errors properly, define what to return and what to catch and send to sentry. https://github.com/ipfs-shipyard/nft.storage/pull/510
- [x] pinning services api needs to send error to sentry, because there we dont use the normal throw error flow. https://github.com/ipfs-shipyard/nft.storage/pull/512
- [x] add uploads deleted_at, update select to account for deleted_at and change the `ON CONFLICT` clause in `upload_fn` https://github.com/ipfs-shipyard/nft.storage/pull/551
- [x] Dont delete auth_keys use `deleted_at` because uploads needs auth_key.id https://github.com/ipfs-shipyard/nft.storage/pull/539
- [x] Define max number of item returned in the list endpoints (nft list and pins list) https://github.com/ipfs-shipyard/nft.storage/pull/493
- [x] Improve the db ts types setup, where we actually setup with docker, run the schema and get the types.
- [x] #374 https://github.com/ipfs-shipyard/nft.storage/pull/485
- [x] Add new enum value for `service_type` `IpfsCluster2` https://github.com/ipfs-shipyard/nft.storage/pull/494 / https://github.com/ipfs-shipyard/nft.storage/pull/509
- [x] Move v1 endpoints to root https://github.com/ipfs-shipyard/nft.storage/pull/534

## Diagram

<img width="1777" alt="Screenshot 2021-10-06 at 10 55 52" src="https://user-images.githubusercontent.com/152863/136181978-57e63284-09d1-4780-9115-60d111680e37.png">

https://dbdiagram.io/d/615d7356940c4c4eec87e2be

**Comment by Gozala** [comment]
Plan of action

- #377 
- #385
- #386

**Comment by alanshaw** [comment]
Things to verify on staging:

* [ ] Test register/login via email
* [ ] Test register/login via github
* [ ] Test logging in with existing "_email_ user" still works
* [ ] Test logging in with existing "_github_ user" still works
* [ ] Test creating an auth key
* [ ] Test deleting an auth key (does not appear in list that it can no longer be used)
* [ ] Test uploading a blob
* [ ] Test uploading a directory
* [ ] Test uploading a car
* [ ] Test uploading partial cars
* [ ] Test uploading an NFT
* [ ] Test uploading with existing key (from before migration) and new key
* [ ] Test deleting an upload (it gets deleted_at set and does not appear in files listing)
* [ ] Test re-uploading the same file twice
* [ ] Test re-uploading a previously deleted file
* [ ] Test pinning a CID
* [ ] Test files listing
